### ISSUE TITLE
[Epic] Authentication & Authorization

### ISSUE THREAD

**Issue by Ayman-tron** [bizz84/flutter-firebase-masterclass#10]
# Epic: Authentication and Authorization Flows

## Description
This Epic covers the entire authentication and authorization flows in the app.

## Tasks
- [ ] Implement login with email link (#1)
- [ ] Implement login with Apple (#2)
- [ ] Implement login with Google (#3)

**Comment by Ayman-tron** [comment]
Issue opened accidentally, I thought I was working on my own repository, apologies for any inconvenience.
